before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -s -w -X "main.Version={{ .Tag }}"
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
  ignore:
    - goos: darwin
      goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
dockers:
  - image_templates:
      - "dukeman/wioctl:{{ .Tag }}"
