apiVersion: apps/v1
kind: Deployment
metadata:
  name: wioctl-deployment
  labels:
    app: wioctl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wioctl
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9001'
    spec:
      containers:
        - name: wioctl
          image: dukeman/wioctl:v0.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
              name: metrics
          args:
            - run
          volumeMounts:
            - name: wioctl-config
              mountPath: /etc/wioctl
          envFrom:
            - secretRef:
                name: wioctl-secret
      volumes:
        - name: wioctl-config
          configMap:
            name: wioctl-config