# declare ConfigMap as a resource
resources:
  - deployment.yaml

images:
  - name: dukeman/wioctl
    newTag: v0.3.0

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
  - name: wioctl-config
    files:
      - configs/.wioctl.yaml
secretGenerator:
  - name: wioctl-secret
    envs:
      - secret/.env