# declare ConfigMap as a resource
resources:
  - deployment.yaml
  - prometheus.yaml
  - service.yaml
  - svcmonitor.yaml

commonLabels:
  app: wioctl

images:
  - name: dukeman/wioctl
    newTag: v0.4.0

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
  - name: wioctl-config
    files:
      - configs/.wioctl.yaml
secretGenerator:
  - name: wioctl-secret
    envs:
      - secret/.env