apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: wioctl-prometheus
  name: wioctl-prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: wioctl
  prometheusSpec:
    retention: 3w