name: Changelog

on:
  release:
    types: [published]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v1

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_branch: 'develop'

      - name: Push changelog
        uses: docker://whizark/chandler
        env:
          CHANDLER_GITHUB_API_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        with:
          args: push

