name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: docker login
        uses: azure/docker-login@v1
        with:
          username: dukeman
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      -
        name: generate-release-changelog
        uses: docker://ferrarimarco/github-changelog-generator:1.15.0.pre.beta
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          SRC_PATH: /github/workspace
        with:
          args: -u gabeduke -p wioctl --release-branch release
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --release-notes=CHANGELOG.md
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
